"""PNG map rendering: the same confirmed colour model as terminal.py
(desert yellow paper, sea as the one distinct paper colour, unit ink by
nationality — BUILD_SPEC.md §8), drawn as an actual image instead of ANSI
text.

Why this module exists: `data/terrain_authentic.png` (a reference asset
bundled with the extraction package) uses a distinct colour for each of the
16 terrain codes. That palette is **not** recovered game data — the real
per-terrain-type paper table (0xD80E) was never decoded beyond "mostly
PAPER 6 = desert yellow" (see graphics.json, BUILD_SPEC.md §8, and
reference/prospects.md #12, still open). `terrain_authentic.png`'s rainbow
legend was generated by the extraction tooling purely for human legibility
while reverse-engineering the map layout; it was never meant to represent
the original's in-game palette, so a faithful renderer should NOT try to
match it. This module renders the *confirmed* model instead: this is a
deliberate fidelity choice, not an oversight -- see NOTES.md.

Only this module needs Pillow (`pip install desert-rats[image]` /
`pyproject.toml`'s `image` extra); the rest of the engine has zero
third-party dependencies, and the terminal renderer remains the
dependency-free default.
"""
from __future__ import annotations

from typing import Iterable, Optional

from ..board import Board, DESERT, ROAD, SEA, VIEWPORT_SIZE
from ..data import Nationality
from ..units import Unit

try:
    from PIL import Image, ImageDraw, ImageFont
except ImportError as exc:  # pragma: no cover - exercised only without Pillow
    raise ImportError(
        "render.image requires Pillow: pip install desert-rats[image]"
    ) from exc

# Standard ZX Spectrum hardware RGB values (graphics.json's zx_palette
# names -- these are the well-known hardware colour numbers, not a guess).
_ZX_RGB = {
    0: (0, 0, 0),        # black
    1: (0, 0, 214),      # blue
    2: (214, 0, 0),      # red
    3: (214, 0, 214),    # magenta
    4: (0, 214, 0),      # green
    5: (0, 214, 214),    # cyan
    6: (214, 214, 0),    # yellow
    7: (214, 214, 214),  # white
}
_ZX_BRIGHT_BONUS = 41  # BUILD_SPEC.md §8: "+brightness"


def _zx(code: int, bright: bool = False) -> tuple:
    r, g, b = _ZX_RGB[code]
    if bright and code != 0:
        r, g, b = (min(255, c + _ZX_BRIGHT_BONUS) for c in (r, g, b))
    return (r, g, b)


# BUILD_SPEC.md §8 / graphics.json side_ink_table: British=blue(1),
# German=black(0), Italian=magenta(3). German rendered bright-black/grey
# for the same legibility reason palette.py's ANSI mapping does (pure
# black is invisible against the desert-yellow paper too) -- a display
# substitution, not a rules change; SPECTRUM_INK there stays the
# provenance record.
NATION_COLOUR = {
    Nationality.BRITISH: _zx(1, bright=True),
    Nationality.GERMAN: (70, 70, 70),
    Nationality.ITALIAN: _zx(3, bright=True),
}

PAPER_DESERT = _zx(6)  # confirmed: "mostly PAPER 6 = desert yellow"
PAPER_SEA = _zx(1, bright=True)  # the one confirmed distinct paper (§8)
# Roads (terrain type 5) are real, confirmed cell data (BUILD_SPEC.md §5.2)
# but their *paper colour* isn't part of the recovered attribute table --
# drawing them as a thin dark line is a legibility aid over real position
# data, not a colour claim about the original.
ROAD_LINE = (90, 78, 40)

GRID_LINE = (0, 0, 0, 40)  # faint, alpha-blended cell separators


def _terrain_colour(terrain_type: int) -> tuple:
    return PAPER_SEA if terrain_type == SEA else PAPER_DESERT


def _build_occupancy(units: Iterable[Unit]) -> dict:
    occupancy = {}
    for unit in units:
        if unit.is_destroyed:
            continue
        for cell in unit.footprint_cells():
            occupancy[cell] = unit
    return occupancy


def _load_font(size: int) -> "ImageFont.ImageFont":
    try:
        return ImageFont.truetype("DejaVuSans-Bold.ttf", size)
    except OSError:
        return ImageFont.load_default()


def render_board_image(
    units: Iterable[Unit],
    board: Board,
    origin: Optional[tuple] = None,
    size: Optional[int] = None,
    cell_px: int = 12,
) -> "Image.Image":
    """Render a viewport (or the whole board if origin/size are None) to a
    Pillow Image: desert/sea paper, road lines, and 2x2/1x1 unit counters
    coloured by nationality with a strength label -- BUILD_SPEC.md §8's
    confirmed model, actually visible instead of raw ANSI escapes.
    """
    if origin is None:
        origin_x, origin_y = 0, 0
        width, height = board.width, board.height
    else:
        origin_x, origin_y = origin
        width = height = size if size is not None else VIEWPORT_SIZE

    occupancy = _build_occupancy(units)
    img = Image.new("RGB", (width * cell_px, height * cell_px), PAPER_DESERT)
    draw = ImageDraw.Draw(img, "RGBA")

    for gy in range(height):
        for gx in range(width):
            x, y = origin_x + gx, origin_y + gy
            px0, py0 = gx * cell_px, gy * cell_px
            px1, py1 = px0 + cell_px, py0 + cell_px
            if not board.in_bounds(x, y):
                continue
            terrain_type = board.terrain_at(x, y)
            draw.rectangle([px0, py0, px1, py1], fill=_terrain_colour(terrain_type))
            if terrain_type == ROAD:
                draw.line([px0, py0 + cell_px // 2, px1, py0 + cell_px // 2], fill=ROAD_LINE, width=max(1, cell_px // 6))
            draw.rectangle([px0, py0, px1, py1], outline=GRID_LINE, width=1)

    font = _load_font(max(8, cell_px - 2))
    drawn_units = set()
    for gy in range(height):
        for gx in range(width):
            x, y = origin_x + gx, origin_y + gy
            unit = occupancy.get((x, y))
            if unit is None or unit.oob_index in drawn_units:
                continue
            drawn_units.add(unit.oob_index)
            cells = list(unit.footprint_cells())
            xs = [c[0] for c in cells]
            ys = [c[1] for c in cells]
            px0 = (min(xs) - origin_x) * cell_px
            py0 = (min(ys) - origin_y) * cell_px
            px1 = (max(xs) - origin_x + 1) * cell_px
            py1 = (max(ys) - origin_y + 1) * cell_px
            colour = NATION_COLOUR[unit.nationality]
            draw.rectangle([px0 + 1, py0 + 1, px1 - 1, py1 - 1], fill=colour, outline=(0, 0, 0))
            label = str(unit.strength)
            tw = draw.textlength(label, font=font) if hasattr(draw, "textlength") else font.getsize(label)[0]
            draw.text(
                (px0 + (px1 - px0 - tw) / 2, py0 + (py1 - py0) / 2 - font.size / 2),
                label,
                fill=(255, 255, 255),
                font=font,
            )

    return img


def save_board_image(
    units: Iterable[Unit],
    board: Board,
    path: str,
    origin: Optional[tuple] = None,
    size: Optional[int] = None,
    cell_px: int = 12,
) -> str:
    """Render and save to `path` (any Pillow-supported extension); returns
    `path` for convenient chaining.
    """
    img = render_board_image(units, board, origin=origin, size=size, cell_px=cell_px)
    img.save(path)
    return path
